Repository ConcealNetwork/conceal-core, pull requests merged in 2021-12, with the labels that each got.

#236 SonarCloud code smell minors
  src/BlockchainExplorer/BlockchainExplorer.cpp
  src/CryptoNoteCore/Miner.cpp
  src/CryptoNoteCore/OnceInInterval.h
  src/CryptoNoteCore/TransactionPool.cpp
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
  src/Logging/LoggerMessage.cpp
  src/Mnemonics/language_base.h
  src/NodeRpcProxy/NodeRpcProxy.cpp
  src/P2p/NetNode.cpp
  src/Wallet/PoolRpcServer.cpp
  src/Wallet/WalletRpcServer.cpp
  src/WalletLegacy/WalletTransactionSender.cpp
  src/crypto/keccak.c
Labels: enhancement

#237 Restore tests and fix some warnings
  .github/workflows/check.yml
  CMakeLists.txt
  src/Common/FileMappedVector.h
  src/Common/Varint.h
  src/CryptoNoteCore/BlockIndex.cpp
  src/CryptoNoteCore/Blockchain.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/Currency.cpp
  src/CryptoNoteCore/TransactionPool.cpp
  src/CryptoNoteCore/UpgradeDetector.h
  src/HTTP/HttpParser.cpp
  src/HTTP/HttpResponse.cpp
  src/Serialization/KVBinaryInputStreamSerializer.cpp
  src/SimpleWallet/SimpleWallet.cpp
  src/Transfers/TypeHelpers.h
  src/crypto/chacha8.h
  tests/CMakeLists.txt
  tests/IntegrationTestLib/InProcTestNode.cpp
  tests/IntegrationTests/Node.cpp
Labels: bug, enhancement

#238 v6.5.2
  .github/workflows/check.yml
  CMakeLists.txt
  README.md
  SECURITY.md
  src/BlockchainExplorer/BlockchainExplorer.cpp
  src/Common/FileMappedVector.h
  src/Common/Varint.h
  src/CryptoNoteCore/BlockIndex.cpp
  src/CryptoNoteCore/Blockchain.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/Currency.cpp
  src/CryptoNoteCore/Miner.cpp
  src/CryptoNoteCore/OnceInInterval.h
  src/CryptoNoteCore/TransactionPool.cpp
  src/CryptoNoteCore/UpgradeDetector.h
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
  src/HTTP/HttpParser.cpp
  src/HTTP/HttpResponse.cpp
  src/Logging/LoggerMessage.cpp
  src/Mnemonics/language_base.h
  src/NodeRpcProxy/NodeRpcProxy.cpp
  src/P2p/NetNode.cpp
  src/Serialization/BinaryInputStreamSerializer.cpp
  src/Serialization/KVBinaryInputStreamSerializer.cpp
  src/SimpleWallet/SimpleWallet.cpp
  src/Transfers/TypeHelpers.h
  src/Wallet/PoolRpcServer.cpp
  src/Wallet/WalletRpcServer.cpp
  src/WalletLegacy/WalletTransactionSender.cpp
  src/crypto/chacha8.h
  src/crypto/keccak.c
  tests/CMakeLists.txt
  tests/IntegrationTestLib/InProcTestNode.cpp
  tests/IntegrationTests/Node.cpp
Labels: enhancement, upgrade, fixes

#253 Fix Payment Service Ringsize
  src/ConnectivityTool/ConnectivityTool.cpp
  src/PaymentGate/PaymentServiceJsonRpcMessages.h
Labels: fixes
